### PR TITLE
Allow attribute transformations in SELECT clause

### PR DESCRIPTION
**Pull request by khageshpatel**
Implements transformation on attributes. Currently only implements format(size,'kb'/'mb'/'gb'), upper, fullpath but other functions can easily be added. Example query:

fsql "select format(size,'kb'), upper(fullpath(name)) from ."

### CODE REVIEW

**Comment by kshvmdn** [comment]
For #17.

**Comment by kshvmdn** [comment]
I've tested this and it works pretty well; some minor problems (like `mode` being empty), but no worries, will add a full review in the next day or so.

I'm going to play around with the code and see if I can add support for WHERE attributes as well as clean-up the logic a little bit.

**Comment by kshvmdn** [comment]
An update on this:

I thought it'd be a better idea to build this against the new parser structure (introduced in [feature/subquery](https://github.com/kshvmdn/fsql/tree/feature/subquery)), so I've made some changes and pushed those to [feature/attribute-modifiers](https://github.com/kshvmdn/fsql/tree/feature/attribute-modifiers) and plan to work on this feature in that branch.

**Comment by khageshpatel** [comment]
@kshvmdn Thanks

**Comment by kshvmdn** [comment]
Merged in 09ea293713036930690a399e4b6951901de7c19f!

**Pull request closed without merging**
